# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"findpos": "00_core.ipynb",
         "isstrictlyascending": "00_core.ipynb",
         "alpha": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://CaptainSifff.github.io/pysplitting/"

git_url = "https://github.com/CaptainSifff/pysplitting/tree/master/"

def custom_doc_links(name): return None
